config/routes.rb
Anibeez::Application.routes.draw do
  

  resources :activities do
  resources :comments

  end

  resources :bookmarks 

  resources :activities
 

  resources :bookmarks do
  get "show_links", :on => :member
  end

    resources:links
  
  
  devise_for :views
  
  devise_for :users, :controllers => {:registrations => "users/registrations",:sessions => "users/sessions"}

  devise_for :users 
  resources :users

  get "home/index"
  root :to => 'home#index'
   
end

 

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base

attr_accessible :name
 
  has_many :links
attr_accessible :avatar
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "10x10>" }
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
 layout "bookmarks" 
# GET /bookmarks
  # GET /bookmarks.json
  def index

  @search = Bookmark.search(params[:search])
  @bookmarks = @search.all
    @links = Link.all
 @user=current_user

    @search = Bookmark.search(params[:search])
    @bookmarks = @search.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bookmarks }
    end
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
 
    @bookmark = Bookmark.find(params[:id]) 
    @links = Link.all
    @book = Bookmark.find(params[:id]) 
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bookmark }
    end
  end

  # GET /bookmarks/new
  # GET /bookmarks/new.json
  def new  

    @bookmark = Bookmark.new
    @links = Link.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bookmark }
    end
  end

  # GET /bookmarks/1/edit
  def edit

    @bookmark = Bookmark.find(params[:id])
    @links = Link.all
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create

    @bookmark = Bookmark.new(params[:bookmark])
    @link = Link.new(params[:link])
    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to bookmarks_path, notice: 'Bookmark was successfully created.' }
        format.json { render json: @bookmark, status: :created, location: @bookmark }
      else
        format.html { render action: "new" }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bookmarks/1
  # PUT /bookmarks/1.json

  def update
 
    @bookmark = Bookmark.find(params[:id])
    respond_to do |format|
      if @bookmark.update_attributes(params[:bookmark])
        format.html { redirect_to bookmarks_path, notice: 'Bookmark was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
   
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    respond_to do |format|
      format.html { redirect_to bookmarks_url }
      format.json { head :ok }
    end
  end


# GET /links/1
def show_links  
 
    @book = Bookmark.find(params[:id]) 
 end

  def show_links  


   @book = Bookmark.find(params[:id])
end

  end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_form.html.erb
<%= form_for(@bookmark) do |f| %>
  <% if @bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
      <% @bookmark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/bookmarks/edit.html.erb
<html>

<head>

<title>ANIBEES</title>
<!--Include the jQuery plugin's file-->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
 
<script>
  $(document).ready(function() {
    $("input#autocomplete").autocomplete({
    source: ["name1", "name2", "name3", "name4", "name5", "name6", "name7","name8","name9","name10","name11","name12"]
});
});
</script>
<!--Include the css file-->

<link rel="stylesheet" type="text/css" href="css/styles.css"/>



</head>

<body>

<div class="home"><!--home container starts-->

<div id="header"><!--Header starts-->

  <div class="logo"><a href="#" title="Anibees"><img src="/assets/logo.png" alt="Anibees logo"/></a></div>
 
   <div class="table"><table><!--table content starts-->

	<tr>
 
	  <td>&nbsp;</td>

	  <td><font color="#eee">Follow us:</font></td>

         

	  <td><a href="#"><img src="/assets/Twitter.png" height="24" width="24"/></a></td>

	  <td><a href="#"><img src="/assets/Facebook.png" height="24" width="24"/></a></td>

	  <td><a href="#"><img src="/assets/LinkedIn.png" height="24" width="24"/></a></td>

        </tr>

  </table>

   </div><!--table content ends-->

</div><!--header ends-->

<div id="main_container"><!--main_container starts-->


 <div id="middlebg"><!--middlebg starts-->


  <div id="body_content"><!--body_content starts-->



   <div id="innerbox"><!--innerbox1 starts-->

    <div class="left"><!--inner left starts-->

<div style="padding:15px;margin-left:25px">
<img src="#" width="150" height="150" title="User Photo">
</div>
	<div id="navigation">
<%= image_tag @user.avatar.url(:medium) %></br>
    	<ul class="top-level">
        <li><%= link_to 'Update profile', edit_user_registration_path %></li>
        <li><%= link_to 'Recent Activities', activities_path  %></li>
        <li><%= link_to 'Bookmarks', bookmarks_path  %></li>
        <li><a href="#">FRIENDS LIST</a></li>
        <li><a href="#">PRESENTATIONS</a></li>
<br/>
<div style="margin-left:3px;">
<input id="autocomplete"/ size="18px"><br /><!--autocomplete -->
<select name=memlist size=10 onChange="showmem(this.form )" style="width:215px;">
<option selected value="John Smith|password|mainpage|">Name1
<option value="Peter Jones|theirpwd|endpages|">Name2
<option value="Sue Brown|asdfvcxz|nowheres|">Name3
<option value="Sally West|zaqxswde|logintop|">Name4
<option value="Sally West|zaqxswde|logintop|">Name5
<option value="Sally West|zaqxswde|logintop|">Name6
<option value="Sally West|zaqxswde|logintop|">Name7
<option value="Sally West|zaqxswde|logintop|">Name8
<option value="Sally West|zaqxswde|logintop|">Name9
<option value="Sally West|zaqxswde|logintop|">Name10
<option value="Sally West|zaqxswde|logintop|">Name11
</select>
</div>
 </ul>
	</div>

    </div><!--inner left ends-->

   </div><!--innerbox1 ends-->

<div id="innerbox"><!--innerbox2 starts-->
 <div class="right"><!--inner right starts-->
<div style="margin:50px 0px 0px 0px;">
	
<h1>Editing bookmark</h1>

<%= render 'form' %>


<%= link_to 'Back', bookmarks_path %>


</form>
</div>

 </div><!--inner right ends-->
</div><!--innerbox2 ends-->

</div><!--body_content ends-->
</div><!--middlebg ends-->

<div id="footer"><!--footer starts-->
  <span>Copyright &copy; 2012 Anibees</span>
</div><!--footer ends-->

</div><!--main_container ends-->
</div> <!--home container ends-->

</body>

</html>

app/views/bookmarks/index.html.erb
<html>

<head>

<title>ANIBEES</title>
<!--Include the jQuery plugin's file-->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
 
<script>
  $(document).ready(function() {
    $("input#autocomplete").autocomplete({
    source: ["name1", "name2", "name3", "name4", "name5", "name6", "name7","name8","name9","name10","name11","name12"]
});
});
</script>
<!--Include the css file-->

<link rel="stylesheet" type="text/css" href="css/styles.css"/>



</head>

<body>

<div class="home"><!--home container starts-->

<div id="header"><!--Header starts-->

  <div class="logo"><a href="#" title="Anibees"><img src="/assets/logo.png" alt="Anibees logo"/></a></div>
 
   <div class="table"><table><!--table content starts-->

	<tr>
 
	  <td>&nbsp;</td>

	  <td><font color="#eee">Follow us:</font></td>

         

	  <td><a href="#"><img src="/assets/Twitter.png" height="24" width="24"/></a></td>

	  <td><a href="#"><img src="/assets/Facebook.png" height="24" width="24"/></a></td>

	  <td><a href="#"><img src="/assets/LinkedIn.png" height="24" width="24"/></a></td>

        </tr>

  </table>

   </div><!--table content ends-->

</div><!--header ends-->

<div id="main_container"><!--main_container starts-->


 <div id="middlebg"><!--middlebg starts-->


  <div id="body_content"><!--body_content starts-->



   <div id="innerbox"><!--innerbox1 starts-->

    <div class="left"><!--inner left starts-->

<div style="padding:15px;margin-left:25px">
<img src="#" width="150" height="150" title="User Photo">
</div>
	<div id="navigation">
<%= image_tag @user.avatar.url(:medium) %></br>
    	<ul class="top-level">
        <li><%= link_to 'Update profile', edit_user_registration_path %></li>
        <li><%= link_to 'Recent Activities', activities_path  %></li>
        <li><%= link_to 'Bookmarks', bookmarks_path  %></li>
        <li><a href="#">FRIENDS LIST</a></li>
        <li><a href="#">PRESENTATIONS</a></li>
<br/>
<div style="margin-left:3px;">
<input id="autocomplete"/ size="18px"><br /><!--autocomplete -->
<select name=memlist size=10 onChange="showmem(this.form )" style="width:215px;">
<option selected value="John Smith|password|mainpage|">Name1
<option value="Peter Jones|theirpwd|endpages|">Name2
<option value="Sue Brown|asdfvcxz|nowheres|">Name3
<option value="Sally West|zaqxswde|logintop|">Name4
<option value="Sally West|zaqxswde|logintop|">Name5
<option value="Sally West|zaqxswde|logintop|">Name6
<option value="Sally West|zaqxswde|logintop|">Name7
<option value="Sally West|zaqxswde|logintop|">Name8
<option value="Sally West|zaqxswde|logintop|">Name9
<option value="Sally West|zaqxswde|logintop|">Name10
<option value="Sally West|zaqxswde|logintop|">Name11
</select>
</div>
 </ul>
	</div>

    </div><!--inner left ends-->

   </div><!--innerbox1 ends-->

<div id="innerbox"><!--innerbox2 starts-->
 <div class="right"><!--inner right starts-->
<div style="margin:50px 0px 0px 0px;">
	


<div align="center">
<h1>Display Bookmarks</h1>

<table>
  <%= form_for @search do |f| %>
    <%= f.label :name_contains, "Search by name of the book:" %>&nbsp;
    <%= f.text_field :name_contains %>&nbsp;
    <%= f.submit %>
<% end %><br /><br />
<% @bookmarks.each do |bookmark| %>
  <tr>
    <td><%=  link_to bookmark.name, show_links_bookmark_path(:id => bookmark.id) %></td> 
    <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %>  || 
    <%= link_to 'Destroy', bookmark, confirm: 'Are you sure?', method: :delete %></td>
<% end %>

</table>

</div>
<br />


<%= link_to 'Add Bookmark', new_bookmark_path %>

</form>
</div>

 </div><!--inner right ends-->
</div><!--innerbox2 ends-->

</div><!--body_content ends-->
</div><!--middlebg ends-->

<div id="footer"><!--footer starts-->
  <span>Copyright &copy; 2012 Anibees</span>
</div><!--footer ends-->

</div><!--main_container ends-->
</div> <!--home container ends-->

</body>

</html>

app/views/bookmarks/new.html.erb
<html>

<head>

<title>ANIBEES</title>
<!--Include the jQuery plugin's file-->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
 
<script>
  $(document).ready(function() {
    $("input#autocomplete").autocomplete({
    source: ["name1", "name2", "name3", "name4", "name5", "name6", "name7","name8","name9","name10","name11","name12"]
});
});
</script>
<!--Include the css file-->

<link rel="stylesheet" type="text/css" href="css/styles.css"/>



</head>

<body>

<div class="home"><!--home container starts-->

<div id="header"><!--Header starts-->

  <div class="logo"><a href="#" title="Anibees"><img src="/assets/logo.png" alt="Anibees logo"/></a></div>
 
   <div class="table"><table><!--table content starts-->

	<tr>
 
	  <td>&nbsp;</td>

	  <td><font color="#eee">Follow us:</font></td>

         

	  <td><a href="#"><img src="/assets/Twitter.png" height="24" width="24"/></a></td>

	  <td><a href="#"><img src="/assets/Facebook.png" height="24" width="24"/></a></td>

	  <td><a href="#"><img src="/assets/LinkedIn.png" height="24" width="24"/></a></td>

        </tr>

  </table>

   </div><!--table content ends-->

</div><!--header ends-->

<div id="main_container"><!--main_container starts-->


 <div id="middlebg"><!--middlebg starts-->


  <div id="body_content"><!--body_content starts-->



   <div id="innerbox"><!--innerbox1 starts-->

    <div class="left"><!--inner left starts-->

<div style="padding:15px;margin-left:25px">
<img src="#" width="150" height="150" title="User Photo">
</div>
	<div id="navigation">
<%= image_tag @user.avatar.url(:medium) %></br>
    	<ul class="top-level">
       <li><%= link_to 'Update profile', edit_user_registration_path %></li>
        <li><%= link_to 'Recent Activities', activities_path  %></li>
        <li><%= link_to 'Bookmarks', bookmarks_path  %></li>
        <li><a href="#">FRIENDS LIST</a></li>
        <li><a href="#">PRESENTATIONS</a></li>
<br/>
<div style="margin-left:3px;">
<input id="autocomplete"/ size="18px"><br /><!--autocomplete -->
<select name=memlist size=10 onChange="showmem(this.form )" style="width:215px;">
<option selected value="John Smith|password|mainpage|">Name1
<option value="Peter Jones|theirpwd|endpages|">Name2
<option value="Sue Brown|asdfvcxz|nowheres|">Name3
<option value="Sally West|zaqxswde|logintop|">Name4
<option value="Sally West|zaqxswde|logintop|">Name5
<option value="Sally West|zaqxswde|logintop|">Name6
<option value="Sally West|zaqxswde|logintop|">Name7
<option value="Sally West|zaqxswde|logintop|">Name8
<option value="Sally West|zaqxswde|logintop|">Name9
<option value="Sally West|zaqxswde|logintop|">Name10
<option value="Sally West|zaqxswde|logintop|">Name11
</select>
</div>
 </ul>
	</div>

    </div><!--inner left ends-->

   </div><!--innerbox1 ends-->

<div id="innerbox"><!--innerbox2 starts-->
 <div class="right"><!--inner right starts-->
<div style="margin:50px 0px 0px 0px;">
	

<h1>New Bookmark</h1>

<%= render 'form' %>


<%= link_to 'Back', bookmarks_path %>


</form>
</div>

 </div><!--inner right ends-->
</div><!--innerbox2 ends-->

</div><!--body_content ends-->
</div><!--middlebg ends-->

<div id="footer"><!--footer starts-->
  <span>Copyright &copy; 2012 Anibees</span>
</div><!--footer ends-->

</div><!--main_container ends-->
</div> <!--home container ends-->

</body>

</html>

app/views/bookmarks/show.html.erb
<html>

<head>

<title>ANIBEES</title>
<!--Include the jQuery plugin's file-->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
 
<script>
  $(document).ready(function() {
    $("input#autocomplete").autocomplete({
    source: ["name1", "name2", "name3", "name4", "name5", "name6", "name7","name8","name9","name10","name11","name12"]
});
});
</script>
<!--Include the css file-->

<link rel="stylesheet" type="text/css" href="css/styles.css"/>



</head>

<body>

<div class="home"><!--home container starts-->

<div id="header"><!--Header starts-->

  <div class="logo"><a href="#" title="Anibees"><img src="/assets/logo.png" alt="Anibees logo"/></a></div>
 
   <div class="table"><table><!--table content starts-->

	<tr>
 
	  <td>&nbsp;</td>

	  <td><font color="#eee">Follow us:</font></td>

         

	  <td><a href="#"><img src="/assets/Twitter.png" height="24" width="24"/></a></td>

	  <td><a href="#"><img src="/assets/Facebook.png" height="24" width="24"/></a></td>

	  <td><a href="#"><img src="/assets/LinkedIn.png" height="24" width="24"/></a></td>

        </tr>

  </table>

   </div><!--table content ends-->

</div><!--header ends-->

<div id="main_container"><!--main_container starts-->


 <div id="middlebg"><!--middlebg starts-->


  <div id="body_content"><!--body_content starts-->



   <div id="innerbox"><!--innerbox1 starts-->

    <div class="left"><!--inner left starts-->

<div style="padding:15px;margin-left:25px">
<img src="#" width="150" height="150" title="User Photo">
</div>
	<div id="navigation">
<%= image_tag @user.avatar.url(:medium) %></br>
    	<ul class="top-level">
       <li><%= link_to 'Update profile', edit_user_registration_path %></li>
        <li><%= link_to 'Recent Activities', activities_path  %></li>
        <li><%= link_to 'Bookmarks', bookmarks_path  %></li>
        <li><a href="#">FRIENDS LIST</a></li>
        <li><a href="#">PRESENTATIONS</a></li>
<br/>
<div style="margin-left:3px;">
<input id="autocomplete"/ size="18px"><br /><!--autocomplete -->
<select name=memlist size=10 onChange="showmem(this.form )" style="width:215px;">
<option selected value="John Smith|password|mainpage|">Name1
<option value="Peter Jones|theirpwd|endpages|">Name2
<option value="Sue Brown|asdfvcxz|nowheres|">Name3
<option value="Sally West|zaqxswde|logintop|">Name4
<option value="Sally West|zaqxswde|logintop|">Name5
<option value="Sally West|zaqxswde|logintop|">Name6
<option value="Sally West|zaqxswde|logintop|">Name7
<option value="Sally West|zaqxswde|logintop|">Name8
<option value="Sally West|zaqxswde|logintop|">Name9
<option value="Sally West|zaqxswde|logintop|">Name10
<option value="Sally West|zaqxswde|logintop|">Name11
</select>
</div>
 </ul>
	</div>

    </div><!--inner left ends-->

   </div><!--innerbox1 ends-->

<div id="innerbox"><!--innerbox2 starts-->
 <div class="right"><!--inner right starts-->
<div style="margin:50px 0px 0px 0px;">
	

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @bookmark.name %>
</p>


<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>



</form>
</div>

 </div><!--inner right ends-->
</div><!--innerbox2 ends-->

</div><!--body_content ends-->
</div><!--middlebg ends-->

<div id="footer"><!--footer starts-->
  <span>Copyright &copy; 2012 Anibees</span>
</div><!--footer ends-->

</div><!--main_container ends-->
</div> <!--home container ends-->

</body>

</html>

app/views/bookmarks/show_links.html.erb
<html>

<head>

<title>ANIBEES</title>
<!--Include the jQuery plugin's file-->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
 
<script>
  $(document).ready(function() {
    $("input#autocomplete").autocomplete({
    source: ["name1", "name2", "name3", "name4", "name5", "name6", "name7","name8","name9","name10","name11","name12"]
});
});
</script>
<!--Include the css file-->

<link rel="stylesheet" type="text/css" href="css/styles.css"/>



</head>

<body>

<div class="home"><!--home container starts-->

<div id="header"><!--Header starts-->

  <div class="logo"><a href="#" title="Anibees"><img src="/assets/logo.png" alt="Anibees logo"/></a></div>
 
   <div class="table"><table><!--table content starts-->

	<tr>
 
	  <td>&nbsp;</td>

	  <td><font color="#eee">Follow us:</font></td>

         

	  <td><a href="#"><img src="/assets/Twitter.png" height="24" width="24"/></a></td>

	  <td><a href="#"><img src="/assets/Facebook.png" height="24" width="24"/></a></td>

	  <td><a href="#"><img src="/assets/LinkedIn.png" height="24" width="24"/></a></td>

        </tr>

  </table>

   </div><!--table content ends-->

</div><!--header ends-->

<div id="main_container"><!--main_container starts-->


 <div id="middlebg"><!--middlebg starts-->


  <div id="body_content"><!--body_content starts-->



   <div id="innerbox"><!--innerbox1 starts-->

    <div class="left"><!--inner left starts-->

<div style="padding:15px;margin-left:25px">
<img src="#" width="150" height="150" title="User Photo">
</div>
	<div id="navigation">
<%= image_tag @user.avatar.url(:medium) %></br>
    	<ul class="top-level">
        <li><%= link_to 'Update profile', edit_user_registration_path %></li>
        <li><%= link_to 'Recent Activities', activities_path  %></li>
        <li><%= link_to 'Bookmarks', bookmarks_path  %></li>
        <li><a href="#">FRIENDS LIST</a></li>
        <li><a href="#">PRESENTATIONS</a></li>
<br/>
<div style="margin-left:3px;">
<input id="autocomplete"/ size="18px"><br /><!--autocomplete -->
<select name=memlist size=10 onChange="showmem(this.form )" style="width:215px;">
<option selected value="John Smith|password|mainpage|">Name1
<option value="Peter Jones|theirpwd|endpages|">Name2
<option value="Sue Brown|asdfvcxz|nowheres|">Name3
<option value="Sally West|zaqxswde|logintop|">Name4
<option value="Sally West|zaqxswde|logintop|">Name5
<option value="Sally West|zaqxswde|logintop|">Name6
<option value="Sally West|zaqxswde|logintop|">Name7
<option value="Sally West|zaqxswde|logintop|">Name8
<option value="Sally West|zaqxswde|logintop|">Name9
<option value="Sally West|zaqxswde|logintop|">Name10
<option value="Sally West|zaqxswde|logintop|">Name11
</select>
</div>
 </ul>
	</div>

    </div><!--inner left ends-->

   </div><!--innerbox1 ends-->

<div id="innerbox"><!--innerbox2 starts-->
 <div class="right"><!--inner right starts-->
<div style="margin:50px 0px 0px 0px;">
	

<h3>Display Links</h3>

<table>
  <tr>
    <th>Url</th>
    <th>Description</th>&nbsp; &nbsp;
    <th>&nbsp; &nbsp; Bookmark</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
   
<% @book.links.each do |sub| %>
   <tr>
   <td><a href="<%= sub.url %>" target="_blank"><%= sub.url %> </a>  &nbsp; &nbsp;  </td>  
   <td> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= sub.description %> </td> 
   <td> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= sub.bookmark.name %> </td> 
</tr>
<% end %>

</table>

<%= link_to 'All Links', links_path %> &nbsp;&nbsp;&nbsp;&nbsp;
<%= link_to 'Back', bookmarks_path %> &nbsp; &nbsp; &nbsp;
<%= link_to 'New Link', new_link_path %>



</form>
</div>

 </div><!--inner right ends-->
</div><!--innerbox2 ends-->

</div><!--body_content ends-->
</div><!--middlebg ends-->

<div id="footer"><!--footer starts-->
  <span>Copyright &copy; 2012 Anibees</span>
</div><!--footer ends-->

</div><!--main_container ends-->
</div> <!--home container ends-->

</body>

</html>