config/routes.rb
Anibeez::Application.routes.draw do
  

  resources :activities do
  resources :comments

  end

  resources :bookmarks 

  resources :activities
 

  resources :bookmarks do
  get "show_links", :on => :member
  end

    resources:links
  
  
  devise_for :views
  
  devise_for :users, :controllers => {:registrations => "users/registrations",:sessions => "users/sessions"}

  devise_for :users 
  resources :users

  get "home/index"
  root :to => 'home#index'
   
end

 

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :bookmark
  #validates_format_of :url, :with => URI::regexp(%w(http|https ))
  validates :url, :description, :presence => {:message => ' cannot be blank.'}, :allow_blank => true, :length => {:minimum => 2, :maximum => 40}

  validates :url, :format =>{ :with => /^((http|https):\/\/)?[a-z0-9]+([-.]{1}[a-z0-9]+).[a-z]{2,5}(:[0-9]{1,5})?(\/.)?$/ix, :message => " is not valid" }
  validates :url, :uniqueness => true
attr_accessible :avatar
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
layout "links"
  # GET /links
  # GET /links.json
  def index
    
    @links = Link.all
    @bookmarks = Bookmark.all
 @user=current_user
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @links }
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])
    @bookmarks = Bookmark.all
 @user=current_user
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/new
  # GET /links/new.json
  def new
    
    @link = Link.new
    @bookmarks = Bookmark.all
 @user=current_user
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = Link.find(params[:id])
    @bookmarks = Bookmark.all
 @user=current_user
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(params[:link])
    @bookmarks = Bookmark.all
 @user=current_user
    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render json: @link, status: :created, location: @link }
      else
        format.html { render action: "new" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.json
  def update
 @user=current_user
    @link = Link.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
 @user=current_user
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :ok }
    end
  end

end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :bookmark %><br />

    <%= f.collection_select(:bookmark_id, Bookmark.all, :id, :name, {:prompt => true}) %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<html>

<head>

<title>ANIBEES</title>
<!--Include the jQuery plugin's file-->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
 
<script>
  $(document).ready(function() {
    $("input#autocomplete").autocomplete({
    source: ["name1", "name2", "name3", "name4", "name5", "name6", "name7","name8","name9","name10","name11","name12"]
});
});
</script>
<!--Include the css file-->

<link rel="stylesheet" type="text/css" href="css/styles.css"/>
<style type="text/css">

</style>


</head>

<body>

<div class="home"><!--home container starts-->

<div id="header"><!--Header starts-->
  
  <div class="logo"><a href="#" title="Anibees"><img src="/assets/logo.png" alt="Anibees logo"/></a></div>
 
   <div class="table"><table><!--table content starts-->

	<tr>
 
	  <td>&nbsp;</td>

	  <td><font color="#eee">Follow us:</font></td>

         

	  <td><a href="#"><img src="/assets/Twitter.png" height="24" width="24"/></a></td>

	  <td><a href="#"><img src="/assets/Facebook.png" height="24" width="24"/></a></td>

	  <td><a href="#"><img src="/assets/LinkedIn.png" height="24" width="24"/></a></td>

        </tr>

  </table>

   </div><!--table content ends-->

</div><!--header ends-->

<div id="main_container"><!--main_container starts-->


 <div id="middlebg"><!--middlebg starts-->


  <div id="body_content"><!--body_content starts-->



   <div id="innerbox"><!--innerbox1 starts-->

    <div class="left"><!--inner left starts-->

<div style="padding:15px;margin-left:25px">
<img src="#" width="150" height="150" title="User Photo">
</div>
	<div id="navigation">
<%= image_tag @user.avatar.url(:medium) %></br>
    	<ul class="top-level">
        <li><a href="#">USER PROFILE</a></li>
        <li><a href="#">RECENT UPDATES</a></li>
        <li><a href="#">BOOK MARKS</a></li>
        <li><a href="#">FRIENDS LIST</a></li>
        <li><a href="#">PRESENTATIONS</a></li>
<br/>
<div style="margin-left:3px;">
<input id="autocomplete"/ size="18px"><br /><!--autocomplete -->
<select name=memlist size=10 onChange="showmem(this.form )" style="width:215px;">
<option selected value="John Smith|password|mainpage|">Name1
<option value="Peter Jones|theirpwd|endpages|">Name2
<option value="Sue Brown|asdfvcxz|nowheres|">Name3
<option value="Sally West|zaqxswde|logintop|">Name4
<option value="Sally West|zaqxswde|logintop|">Name5
<option value="Sally West|zaqxswde|logintop|">Name6
<option value="Sally West|zaqxswde|logintop|">Name7
<option value="Sally West|zaqxswde|logintop|">Name8
<option value="Sally West|zaqxswde|logintop|">Name9
<option value="Sally West|zaqxswde|logintop|">Name10
<option value="Sally West|zaqxswde|logintop|">Name11
</select>
</div>
 </ul>
	</div>

    </div><!--inner left ends-->

   </div><!--innerbox1 ends-->

<div id="innerbox"><!--innerbox2 starts-->
 <div class="right"><!--inner right starts-->
<div style="margin:50px 0px 0px 0px;">
<h1>Listing links</h1>
<table>
  <tr>
    <th>Url</th>
    <th>Description</th>
    
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @links.each do |link| %>
  <tr>
    <td> &nbsp; &nbsp;&nbsp;<a href="<%= link.url %>" target="_blank"><%= link.url %> </a></td> 
    <td><%= link.description %></td> &nbsp; &nbsp; &nbsp; 
     
    <td><%= link_to 'Edit', edit_link_path(link) %> ||</td>
    <td><%= link_to 'Destroy', link, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'BACK', bookmarks_path %> &nbsp; &nbsp; &nbsp;
<%= link_to 'New Link', new_link_path %>
	
</form>
</div>

 </div><!--inner right ends-->
</div><!--innerbox2 ends-->

</div><!--body_content ends-->
</div><!--middlebg ends-->

<div id="footer"><!--footer starts-->
  <span>Copyright &copy; 2012 Anibees</span>
</div><!--footer ends-->

</div><!--main_container ends-->
</div> <!--home container ends-->

</body>

</html>

app/views/links/new.html.erb
<html>

<head>

<title>ANIBEES</title>
<!--Include the jQuery plugin's file-->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
 
<script>
  $(document).ready(function() {
    $("input#autocomplete").autocomplete({
    source: ["name1", "name2", "name3", "name4", "name5", "name6", "name7","name8","name9","name10","name11","name12"]
});
});
</script>
<!--Include the css file-->

<link rel="stylesheet" type="text/css" href="css/styles.css"/>
<style type="text/css">

</style>


</head>

<body>

<div class="home"><!--home container starts-->

<div id="header"><!--Header starts-->

  <div class="logo"><a href="#" title="Anibees"><img src="/assets/logo.png" alt="Anibees logo"/></a></div>
 
   <div class="table"><table><!--table content starts-->

	<tr>
 
	  <td>&nbsp;</td>

	  <td><font color="#eee">Follow us:</font></td>

         

	  <td><a href="#"><img src="/assets/Twitter.png" height="24" width="24"/></a></td>

	  <td><a href="#"><img src="/assets/Facebook.png" height="24" width="24"/></a></td>

	  <td><a href="#"><img src="/assets/LinkedIn.png" height="24" width="24"/></a></td>

        </tr>

  </table>

   </div><!--table content ends-->

</div><!--header ends-->

<div id="main_container"><!--main_container starts-->


 <div id="middlebg"><!--middlebg starts-->


  <div id="body_content"><!--body_content starts-->



   <div id="innerbox"><!--innerbox1 starts-->

    <div class="left"><!--inner left starts-->

<div style="padding:15px;margin-left:25px">
<img src="#" width="150" height="150" title="User Photo">
</div>
	<div id="navigation">
<%= image_tag @user.avatar.url(:medium) %></br>
    	<ul class="top-level">
        <li><a href="#">USER PROFILE</a></li>
        <li><a href="#">RECENT UPDATES</a></li>
        <li><a href="#">BOOK MARKS</a></li>
        <li><a href="#">FRIENDS LIST</a></li>
        <li><a href="#">PRESENTATIONS</a></li>
<br/>
<div style="margin-left:3px;">
<input id="autocomplete"/ size="18px"><br /><!--autocomplete -->
<select name=memlist size=10 onChange="showmem(this.form )" style="width:215px;">
<option selected value="John Smith|password|mainpage|">Name1
<option value="Peter Jones|theirpwd|endpages|">Name2
<option value="Sue Brown|asdfvcxz|nowheres|">Name3
<option value="Sally West|zaqxswde|logintop|">Name4
<option value="Sally West|zaqxswde|logintop|">Name5
<option value="Sally West|zaqxswde|logintop|">Name6
<option value="Sally West|zaqxswde|logintop|">Name7
<option value="Sally West|zaqxswde|logintop|">Name8
<option value="Sally West|zaqxswde|logintop|">Name9
<option value="Sally West|zaqxswde|logintop|">Name10
<option value="Sally West|zaqxswde|logintop|">Name11
</select>
</div>
 </ul>
	</div>

    </div><!--inner left ends-->

   </div><!--innerbox1 ends-->

<div id="innerbox"><!--innerbox2 starts-->
 <div class="right"><!--inner right starts-->
<div style="margin:50px 0px 0px 0px;">

<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'All Links', links_path %> &nbsp;&nbsp;&nbsp;&nbsp;
<%= link_to 'BACK', bookmarks_path %>
	
</form>
</div>

 </div><!--inner right ends-->
</div><!--innerbox2 ends-->

</div><!--body_content ends-->
</div><!--middlebg ends-->

<div id="footer"><!--footer starts-->
  <span>Copyright &copy; 2012 Anibees</span>
</div><!--footer ends-->

</div><!--main_container ends-->
</div> <!--home container ends-->

</body>

</html>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @link.url %>
</p>

<p>
  <b>Description:</b>
  <%= @link.description %>
</p>
<p>
  <b>Bookmark:</b>
  <%= @link.bookmark.name %>
</p>
<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>