config/routes.rb
Anibeez::Application.routes.draw do
  

  resources :activities do
  resources :comments

  end

  resources :bookmarks 

  resources :activities
 

  resources :bookmarks do
  get "show_links", :on => :member
  end

    resources:links
  
  
  devise_for :views
  
  devise_for :users, :controllers => {:registrations => "users/registrations",:sessions => "users/sessions"}

  devise_for :users 
  resources :users

  get "home/index"
  root :to => 'home#index'
   
end

 

app/models/activity.rb
class Activity < ActiveRecord::Base

 
  belongs_to :user
  has_many :comments, :dependent => :destroy

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
     
  
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = Activity.new
    @user = User.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(params[:activity])
@activity.user_id=current_user.id
    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :ok }
    end
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :query %><br />
    <%= f.text_area :query %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<html>

<head>

<title>ANIBEES</title>
<!--Include the jQuery plugin's file-->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
 
<script>
  $(document).ready(function() {
    $("input#autocomplete").autocomplete({
    source: ["name1", "name2", "name3", "name4", "name5", "name6", "name7","name8","name9","name10","name11","name12"]
});
});
</script>
<!--Include the css file-->

<link rel="stylesheet" type="text/css" href="css/styles.css"/>



</head>

<body>

<div class="home"><!--home container starts-->

<div id="header"><!--Header starts-->

  <div class="logo"><a href="#" title="Anibees"><img src="/assets/logo.png" alt="Anibees logo"/></a></div>
 
   <div class="table"><table><!--table content starts-->

	<tr>
 
	  <td>&nbsp;</td>

	  <td><font color="#eee">Follow us:</font></td>

         

	  <td><a href="#"><img src="/assets/Twitter.png" height="24" width="24"/></a></td>

	  <td><a href="#"><img src="/assets/Facebook.png" height="24" width="24"/></a></td>

	  <td><a href="#"><img src="/assets/LinkedIn.png" height="24" width="24"/></a></td>

        </tr>

  </table>

   </div><!--table content ends-->

</div><!--header ends-->

<div id="main_container"><!--main_container starts-->


 <div id="middlebg"><!--middlebg starts-->


  <div id="body_content"><!--body_content starts-->



   <div id="innerbox"><!--innerbox1 starts-->

    <div class="left"><!--inner left starts-->

<div style="padding:15px;margin-left:25px">
<img src="#" width="150" height="150" title="User Photo">
</div>
	<div id="navigation">
    	<ul class="top-level">
        <li><%= link_to 'Update profile', edit_user_registration_path %></li>
        <li><%= link_to 'Recent Activities', activities_path  %></li>
        <li><%= link_to 'Bookmarks', bookmarks_path  %></li>
        <li><a href="#">FRIENDS LIST</a></li>
        <li><a href="#">PRESENTATIONS</a></li>
<br/>
<div style="margin-left:3px;">
<input id="autocomplete"/ size="18px"><br /><!--autocomplete -->
<select name=memlist size=10 onChange="showmem(this.form )" style="width:215px;">
<option selected value="John Smith|password|mainpage|">Name1
<option value="Peter Jones|theirpwd|endpages|">Name2
<option value="Sue Brown|asdfvcxz|nowheres|">Name3
<option value="Sally West|zaqxswde|logintop|">Name4
<option value="Sally West|zaqxswde|logintop|">Name5
<option value="Sally West|zaqxswde|logintop|">Name6
<option value="Sally West|zaqxswde|logintop|">Name7
<option value="Sally West|zaqxswde|logintop|">Name8
<option value="Sally West|zaqxswde|logintop|">Name9
<option value="Sally West|zaqxswde|logintop|">Name10
<option value="Sally West|zaqxswde|logintop|">Name11
</select>
</div>
 </ul>
	</div>

    </div><!--inner left ends-->

   </div><!--innerbox1 ends-->

<div id="innerbox"><!--innerbox2 starts-->
 <div class="right"><!--inner right starts-->
<div style="margin:50px 0px 0px 0px;">
	
<h1>Listing activities</h1>

<table>
  <tr>
    <th>Query</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @activities.each do |activity| %>
  <tr>

    <td><%= activity.query %></td>
    <td><%= activity.user.first_name  %></td>
    <td><%= link_to 'Repply with Comment', activity %></td>
    <% if activity.user_id == current_user.id %>
    <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
    <td><%= link_to 'Destroy', activity, confirm: 'Are you sure?', method: :delete %></td>
    
   <% end %>
</tr>

<% end %>
</table>

<br />

<%= link_to 'New Activity', new_activity_path %>
<%= link_to 'Home', root_path %>



</form>
</div>

 </div><!--inner right ends-->
</div><!--innerbox2 ends-->

</div><!--body_content ends-->
</div><!--middlebg ends-->

<div id="footer"><!--footer starts-->
  <span>Copyright &copy; 2012 Anibees</span>
</div><!--footer ends-->

</div><!--main_container ends-->
</div> <!--home container ends-->

</body>

</html>

app/views/activities/new.html.erb
<html>

<head>

<title>ANIBEES</title>
<!--Include the jQuery plugin's file-->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
 
<script>
  $(document).ready(function() {
    $("input#autocomplete").autocomplete({
    source: ["name1", "name2", "name3", "name4", "name5", "name6", "name7","name8","name9","name10","name11","name12"]
});
});
</script>
<!--Include the css file-->

<link rel="stylesheet" type="text/css" href="css/styles.css"/>



</head>

<body>

<div class="home"><!--home container starts-->

<div id="header"><!--Header starts-->

  <div class="logo"><a href="#" title="Anibees"><img src="/assets/logo.png" alt="Anibees logo"/></a></div>
 
   <div class="table"><table><!--table content starts-->

	<tr>
 
	  <td>&nbsp;</td>

	  <td><font color="#eee">Follow us:</font></td>

         

	  <td><a href="#"><img src="/assets/Twitter.png" height="24" width="24"/></a></td>

	  <td><a href="#"><img src="/assets/Facebook.png" height="24" width="24"/></a></td>

	  <td><a href="#"><img src="/assets/LinkedIn.png" height="24" width="24"/></a></td>

        </tr>

  </table>

   </div><!--table content ends-->

</div><!--header ends-->

<div id="main_container"><!--main_container starts-->


 <div id="middlebg"><!--middlebg starts-->


  <div id="body_content"><!--body_content starts-->



   <div id="innerbox"><!--innerbox1 starts-->

    <div class="left"><!--inner left starts-->

<div style="padding:15px;margin-left:25px">
<img src="#" width="150" height="150" title="User Photo">
</div>
	<div id="navigation">
    	<ul class="top-level">
        <li><%= link_to 'Update profile', edit_user_registration_path %></li>
        <li><%= link_to 'Recent Activities', activities_path  %></li>
        <li><%= link_to 'Bookmarks', bookmarks_path  %></li>
        <li><a href="#">FRIENDS LIST</a></li>
        <li><a href="#">PRESENTATIONS</a></li>
<br/>
<div style="margin-left:3px;">
<input id="autocomplete"/ size="18px"><br /><!--autocomplete -->
<select name=memlist size=10 onChange="showmem(this.form )" style="width:215px;">
<option selected value="John Smith|password|mainpage|">Name1
<option value="Peter Jones|theirpwd|endpages|">Name2
<option value="Sue Brown|asdfvcxz|nowheres|">Name3
<option value="Sally West|zaqxswde|logintop|">Name4
<option value="Sally West|zaqxswde|logintop|">Name5
<option value="Sally West|zaqxswde|logintop|">Name6
<option value="Sally West|zaqxswde|logintop|">Name7
<option value="Sally West|zaqxswde|logintop|">Name8
<option value="Sally West|zaqxswde|logintop|">Name9
<option value="Sally West|zaqxswde|logintop|">Name10
<option value="Sally West|zaqxswde|logintop|">Name11
</select>
</div>
 </ul>
	</div>

    </div><!--inner left ends-->

   </div><!--innerbox1 ends-->

<div id="innerbox"><!--innerbox2 starts-->
 <div class="right"><!--inner right starts-->
<div style="margin:50px 0px 0px 0px;">
	
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

</form>
</div>

 </div><!--inner right ends-->
</div><!--innerbox2 ends-->

</div><!--body_content ends-->
</div><!--middlebg ends-->

<div id="footer"><!--footer starts-->
  <span>Copyright &copy; 2012 Anibees</span>
</div><!--footer ends-->

</div><!--main_container ends-->
</div> <!--home container ends-->

</body>

</html>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Query:</b>
  <%= @activity.query %>
</p>

<p>
  <b>User:</b>
  <%= @activity.user.first_name %>
</p>
<h2>Comments</h2>
<%= render @activity.comments %>

<h2>Add a comment:</h2>
<%= render "comments/form" %>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>